language: node_js
node_js:
  - "lts/*"
  - "node"
  - "8"

script:
  - echo "Running tests against $(node -v) ..."
  - yarn test

jobs:
  include:
    - stage: coverage
      node_js: "lts/*"
      install:
        - yarn install
        - npm install -g codecov codeclimate-test-reporter codacy-coverage
      script:
        - yarn test
        - nyc report --report-dir=coverage/ --reporter=text-lcov > coverage.lcov
        - codecov
        - codeclimate-test-reporter < coverage.lcov
        - codacy-coverage < coverage.lcov
