language: node_js
node_js:
  - "lts/*"
  - "node"
  - "8"
install:
  - yarn install
  - npm install -g codecov codeclimate-test-reporter

script:
  - npm run test
  - nyc report --report-dir=coverage/ --reporter=text-lcov > coverage.lcov
  - codecov
  - codeclimate-test-reporter < coverage.lcov
