language: node_js
node_js:
  - "lts/*"
  - "node"
  - "8"
install:
  - yarn install
  - npm install -g codecov coveralls
script:
  - npm run test
  - nyc report --reporter=json > coverage.json
  - codecov
  - coveralls
